// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_KELVIN_20180193.DAL;

namespace P2_KELVIN_20180193.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211108204352_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_KELVIN_20180193.Entidades.TipoTareas", b =>
                {
                    b.Property<int>("TipoTareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionTipoTarea")
                        .HasColumnType("TEXT");

                    b.Property<int>("TiempoAcumulado")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoTareaId");

                    b.ToTable("TipoTareas");

                    b.HasData(
                        new
                        {
                            TipoTareaId = 1,
                            DescripcionTipoTarea = "Análisis",
                            TiempoAcumulado = 0
                        },
                        new
                        {
                            TipoTareaId = 2,
                            DescripcionTipoTarea = "Diseño",
                            TiempoAcumulado = 0
                        },
                        new
                        {
                            TipoTareaId = 3,
                            DescripcionTipoTarea = "Programación",
                            TiempoAcumulado = 0
                        },
                        new
                        {
                            TipoTareaId = 4,
                            DescripcionTipoTarea = "Prueba",
                            TiempoAcumulado = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
